
package com.custodix.mpi._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-01-27T11:59:07.083+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "AccessDeniedException", targetNamespace = "http://www.custodix.com/MPI/1.0")
public class AccessDeniedException extends Exception {
    
    private com.custodix.mpi._1.AccessDeniedException accessDeniedException;

    public AccessDeniedException() {
        super();
    }
    
    public AccessDeniedException(String message) {
        super(message);
    }
    
    public AccessDeniedException(String message, Throwable cause) {
        super(message, cause);
    }

    public AccessDeniedException(String message, com.custodix.mpi._1.AccessDeniedException accessDeniedException) {
        super(message);
        this.accessDeniedException = accessDeniedException;
    }

    public AccessDeniedException(String message, com.custodix.mpi._1.AccessDeniedException accessDeniedException, Throwable cause) {
        super(message, cause);
        this.accessDeniedException = accessDeniedException;
    }

    public com.custodix.mpi._1.AccessDeniedException getFaultInfo() {
        return this.accessDeniedException;
    }
}
