
package com.custodix.mpi._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-01-27T11:59:07.067+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "DataValidationException", targetNamespace = "http://www.custodix.com/MPI/1.0")
public class DataValidationException extends Exception {
    
    private com.custodix.mpi._1.DataValidationException dataValidationException;

    public DataValidationException() {
        super();
    }
    
    public DataValidationException(String message) {
        super(message);
    }
    
    public DataValidationException(String message, Throwable cause) {
        super(message, cause);
    }

    public DataValidationException(String message, com.custodix.mpi._1.DataValidationException dataValidationException) {
        super(message);
        this.dataValidationException = dataValidationException;
    }

    public DataValidationException(String message, com.custodix.mpi._1.DataValidationException dataValidationException, Throwable cause) {
        super(message, cause);
        this.dataValidationException = dataValidationException;
    }

    public com.custodix.mpi._1.DataValidationException getFaultInfo() {
        return this.dataValidationException;
    }
}
