
package com.custodix.mpi._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-01-27T11:59:07.091+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "NoSuchSourceException", targetNamespace = "http://www.custodix.com/MPI/1.0")
public class NoSuchSourceException extends Exception {
    
    private com.custodix.mpi._1.NoSuchSourceException noSuchSourceException;

    public NoSuchSourceException() {
        super();
    }
    
    public NoSuchSourceException(String message) {
        super(message);
    }
    
    public NoSuchSourceException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchSourceException(String message, com.custodix.mpi._1.NoSuchSourceException noSuchSourceException) {
        super(message);
        this.noSuchSourceException = noSuchSourceException;
    }

    public NoSuchSourceException(String message, com.custodix.mpi._1.NoSuchSourceException noSuchSourceException, Throwable cause) {
        super(message, cause);
        this.noSuchSourceException = noSuchSourceException;
    }

    public com.custodix.mpi._1.NoSuchSourceException getFaultInfo() {
        return this.noSuchSourceException;
    }
}
