
package com.custodix.mpi._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-01-27T11:59:07.075+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "NoSuchPseudonymException", targetNamespace = "http://www.custodix.com/MPI/1.0")
public class NoSuchPseudonymException extends Exception {
    
    private com.custodix.mpi._1.NoSuchPseudonymException noSuchPseudonymException;

    public NoSuchPseudonymException() {
        super();
    }
    
    public NoSuchPseudonymException(String message) {
        super(message);
    }
    
    public NoSuchPseudonymException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchPseudonymException(String message, com.custodix.mpi._1.NoSuchPseudonymException noSuchPseudonymException) {
        super(message);
        this.noSuchPseudonymException = noSuchPseudonymException;
    }

    public NoSuchPseudonymException(String message, com.custodix.mpi._1.NoSuchPseudonymException noSuchPseudonymException, Throwable cause) {
        super(message, cause);
        this.noSuchPseudonymException = noSuchPseudonymException;
    }

    public com.custodix.mpi._1.NoSuchPseudonymException getFaultInfo() {
        return this.noSuchPseudonymException;
    }
}
