
package com.custodix.mpi._1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-01-27T11:59:07.022+01:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "NoSuchResearchProjectException", targetNamespace = "http://www.custodix.com/MPI/1.0")
public class NoSuchResearchProjectException extends Exception {
    
    private com.custodix.mpi._1.NoSuchResearchProjectException noSuchResearchProjectException;

    public NoSuchResearchProjectException() {
        super();
    }
    
    public NoSuchResearchProjectException(String message) {
        super(message);
    }
    
    public NoSuchResearchProjectException(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchResearchProjectException(String message, com.custodix.mpi._1.NoSuchResearchProjectException noSuchResearchProjectException) {
        super(message);
        this.noSuchResearchProjectException = noSuchResearchProjectException;
    }

    public NoSuchResearchProjectException(String message, com.custodix.mpi._1.NoSuchResearchProjectException noSuchResearchProjectException, Throwable cause) {
        super(message, cause);
        this.noSuchResearchProjectException = noSuchResearchProjectException;
    }

    public com.custodix.mpi._1.NoSuchResearchProjectException getFaultInfo() {
        return this.noSuchResearchProjectException;
    }
}
