package com.custodix.mpi._1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-01-27T11:59:07.117+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "PseudonymizationService", 
                  wsdlLocation = "https://pims-dev-trait.custodix.com/pims/services/PseudonymizationService?wsdl",
                  targetNamespace = "http://www.custodix.com/MPI/1.0") 
public class PseudonymizationService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.custodix.com/MPI/1.0", "PseudonymizationService");
    public final static QName PseudonymizationServicePort = new QName("http://www.custodix.com/MPI/1.0", "PseudonymizationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("https://pims-dev-trait.custodix.com/pims/services/PseudonymizationService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PseudonymizationService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://pims-dev-trait.custodix.com/pims/services/PseudonymizationService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PseudonymizationService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PseudonymizationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PseudonymizationService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     *
     * @return
     *     returns PseudonymizationService
     */
    @WebEndpoint(name = "PseudonymizationServicePort")
    public PseudonymizationService getPseudonymizationServicePort() {
        return super.getPort(PseudonymizationServicePort, PseudonymizationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PseudonymizationService
     */
    @WebEndpoint(name = "PseudonymizationServicePort")
    public PseudonymizationService getPseudonymizationServicePort(WebServiceFeature... features) {
        return super.getPort(PseudonymizationServicePort, PseudonymizationService.class, features);
    }

}
