package com.custodix.mpi._1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-01-27T11:59:07.098+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.custodix.com/MPI/1.0", name = "PseudonymizationService")
@XmlSeeAlso({com.custodix.mpi._1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PseudonymizationService {

    @WebResult(name = "linkPseudonymsResponse", targetNamespace = "http://www.custodix.com/MPI/1.0", partName = "linkPseudonymsResponse")
    @WebMethod
    public com.custodix.mpi._1.PseudonymizationResponse linkPseudonyms(
        @WebParam(partName = "linkPseudonyms", name = "linkPseudonyms", targetNamespace = "http://www.custodix.com/MPI/1.0")
        com.custodix.mpi._1.PseudonymLinkingRequest linkPseudonyms
    ) throws NoSuchResearchProjectException, InternalError, DataValidationException, NoSuchPseudonymException, AccessDeniedException;

    @WebResult(name = "requestPseudonymsResponse", targetNamespace = "http://www.custodix.com/MPI/1.0", partName = "requestPseudonymsResponse")
    @WebMethod
    public com.custodix.mpi._1.PseudonymizationResponse requestPseudonyms(
        @WebParam(partName = "requestPseudonyms", name = "requestPseudonyms", targetNamespace = "http://www.custodix.com/MPI/1.0")
        com.custodix.mpi._1.PseudonymizationRequest requestPseudonyms
    ) throws InternalError, DataValidationException, AccessDeniedException;

    @WebResult(name = "enrichResponse", targetNamespace = "http://www.custodix.com/MPI/1.0", partName = "enrichResponse")
    @WebMethod
    public com.custodix.mpi._1.EnrichmentResponse enrich(
        @WebParam(partName = "enrich", name = "enrich", targetNamespace = "http://www.custodix.com/MPI/1.0")
        com.custodix.mpi._1.EnrichmentRequest enrich
    ) throws InternalError, DataValidationException, NoSuchPseudonymException, AccessDeniedException;

    @WebResult(name = "requestLinkingTableResponse", targetNamespace = "http://www.custodix.com/MPI/1.0", partName = "requestLinkingTableResponse")
    @WebMethod
    public com.custodix.mpi._1.LinkingTableResponse requestLinkingTable(
        @WebParam(partName = "requestLinkingTable", name = "requestLinkingTable", targetNamespace = "http://www.custodix.com/MPI/1.0")
        com.custodix.mpi._1.LinkingTableRequest requestLinkingTable
    ) throws NoSuchResearchProjectException, NoSuchSourceException, InternalError, DataValidationException, NoSuchPseudonymException, AccessDeniedException;

    @WebResult(name = "reidentifyResponse", targetNamespace = "http://www.custodix.com/MPI/1.0", partName = "reidentifyResponse")
    @WebMethod
    public com.custodix.mpi._1.ReidentificationResponse reidentify(
        @WebParam(partName = "reidentify", name = "reidentify", targetNamespace = "http://www.custodix.com/MPI/1.0")
        com.custodix.mpi._1.ReidentificationRequest reidentify
    ) throws InternalError, DataValidationException, NoSuchPseudonymException, AccessDeniedException;

    @WebResult(name = "excludeSubjectResponse", targetNamespace = "http://www.custodix.com/MPI/1.0", partName = "excludeSubjectResponse")
    @WebMethod
    public com.custodix.mpi._1.SubjectExclusionResponse excludeSubject(
        @WebParam(partName = "excludeSubject", name = "excludeSubject", targetNamespace = "http://www.custodix.com/MPI/1.0")
        com.custodix.mpi._1.SubjectExclusionRequest excludeSubject
    ) throws InternalError, DataValidationException, AccessDeniedException;
}
